services:
  redis_db:
    container_name: redisdb
    image: redis/redis-stack-server:latest
    command: redis-server /redis.conf --requirepass ${REDIS_PWD}
    volumes:
    - ./redis.conf:/redis.conf
    - ${VOLUME_DIR}/redis_db:/data
    environment:
      REDIS_PWD: ${REDIS_PWD}
      VOLUME_DIR: ${VOLUME_DIR}
  postgres_db:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    volumes:
      - ${VOLUME_DIR}/postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
      VOLUME_DIR: ${VOLUME_DIR}
  flask_app:
    container_name: flaskapp
    image: flaskapp
    depends_on:
      - redis_db
      - postgres_db
    ports:
      - 5000:5000
