CREATE TABLE recipe(
  id SERIAL PRIMARY KEY,
  title VARCHAR(32) UNIQUE
);


CREATE TABLE meal(
  date DATE PRIMARY KEY,
  lunch VARCHAR(32) REFERENCES recipe(title) ON DELETE SET NULL ON UPDATE CASCADE,
  dinner VARCHAR(32) REFERENCES recipe(title) ON DELETE SET NULL ON UPDATE CASCADE
);
